version: '3'

networks:
  gorge-dev:
  gorge-test:

services:
  database:
    image: 'postgres:9.6'
    env_file: .env.development
    networks:
      - gorge-dev
    ports:
      - 15432:5432

  database-testing:
    image: 'postgres:9.6'
    env_file: .env.testing
    networks:
      - gorge-test
    ports:
      - 15433:5432

  redis:
    image: 'redis:3'
    networks:
      - gorge-dev
    ports:
      - 16379:6379

  redis-test:
    image: 'redis:3'
    networks:
      - gorge-test
    ports:
      - 26379:6379
