---
schedule_data_source_updates:
  cron: '* * * * *'
  class: Gorge::Jobs::ScheduleDataSourceUpdates
  queue: schedule_data_source_updates
  args:
  description: 'Schedule updates of data sources which are in need of one.'
