---
schedule_data_source_updates:
  cron: '* * * * *'
  class: Gorge::Jobs::ScheduleDataSourceUpdates
  args:
  description: 'Schedule updates of data sources which are in need of one.'

remove_downloaded_data_files:
  cron: '* * * * *'
  class: Gorge::Jobs::RemoveDownloadedDataFiles
  args:
  description: 'Remove downloaded data files exceeding a certain age.'

reset_pending_updates:
  cron: '* * * * *'
  class: Gorge::Jobs::ResetPendingUpdates
  args:
  description: 'Reset the "update pending" status of data sources after a certain grace period.'

update_player_statistics:
  # Tuesdays at 00:00. This is based on the fact that all data source updates
  # happen on Mondays - but is obviously rather brittle.
  cron: '0 0 * * 2'
  class: Gorge::Jobs::UpdatePlayerStatistics
  args:
  description: 'Update player statistics.'
